test

diff --git a/.github/workflows/build-web-app-image-staging.yml b/.github/workflows/build-web-app-image-staging.yml
--- a/.github/workflows/build-web-app-image-staging.yml
+++ b/.github/workflows/build-web-app-image-staging.yml
@@ -25,10 +25,26 @@ jobs:
         with:
           script: |
             const mergeable = `${{ github.event.client_payload.pull_request.mergeable }}`;
-            const body = mergeable ? "OK" : "PR should be mergeable";
-            github.rest.issues.createComment({
-              issue_number: `${{ github.event.client_payload.github.payload.issue.number }}`,
-              owner: "monkukui",
-              repo: "slash-command-processor",
-              body: body,
-            });
+            if (mergeable === "true") {
+              github.rest.issues.createComment({
+                issue_number: `${{ github.event.client_payload.github.payload.issue.number }}`,
+                owner: "monkukui",
+                repo: "slash-command-processor",
+                body: "ok",
+              });
+            } else {
+              github.rest.issues.createComment({
+                issue_number: `${{ github.event.client_payload.github.payload.issue.number }}`,
+                owner: "monkukui",
+                repo: "slash-command-processor",
+                body: "ng",
+              });
+            }
+      - name: Error handling
+        if: github.event.client_payload.pull_request.mergeable == 'false'
+        run: |
+          echo "Error handling"
+          exit 1
+      - name: On success
+        run: |
+          echo "Success"
